# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test',
                'doc_host': 'https://patelarmankumar.github.io',
                'git_url': 'https://github.com/patelarmankumar/nbdev_test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': { 'nbdev_test.core.arman_function': ('core.html#arman_function', 'nbdev_test/core.py'),
                                 'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')}}}
