# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'arman_function']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def arman_function() -> str: 
    """
    This is Doc String.

    Hello. 
    How are you?
    """

    return "This is arman_function"
